# Copyright 2022 Kamesh Sampath<kamesh.sampath@hotmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#  APKO DRONE PLUGIN
#
# This image configuration is used by the apko-drone plugin to build 
# OCI container images from APK packages
#
package:
  name: amazon-ecr-credential-helper
  version:  0.6.0
  epoch: 0
  description: "Automatically gets credentials for Amazon ECR on docker push/docker pull"
  target-architecture:
    - arm64
    - amd64
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
  packages:
     - go

pipeline:
  - uses: go/install
    with:
      package: github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@latest
  - runs: |
      ${{targets.destdir}}/usr/bin/docker-credential-ecr-login -v
  - uses: strip