# Copyright 2022 Kamesh Sampath<kamesh.sampath@hotmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#  APKO DRONE PLUGIN
#
# This image configuration is used by the apko-drone plugin to build
# OCI container images from APK packages
#
package:
  name: docker-credential-gcr
  version: 2.1.6
  epoch: 0
  description: "A Docker credential helper for GCR users"
  target-architecture:
    - arm64
    - amd64
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
 
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
  packages:
     - go
     - busybox
     - ca-certificates-bundle
     - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/docker-credential-gcr
      branch: v${{package.version}}
      destination: docker-credential-gcr
  - uses: go/build
    with:
      packages: .
      output: docker-credential-gcr
      modroot: docker-credential-gcr
      ldflags: "-s -w -X github.com/GoogleCloudPlatform/docker-credential-gcr/config.Version=${{package.version}}"
  - runs: |
      set +x
      "${{targets.destdir}}"/usr/bin/docker-credential-gcr version | grep -i "Google Container Registry Docker credential helper ${{package.version}}"
  - uses: strip
