kind: pipeline
type: docker
name: default

steps:
  - name: build image
    image: kameshsampath/apko-drone-plugin:latest
    pull: if-not-exists
    settings:
      config_file: image.yaml
      image_repo: 
        from_secret: image_repo
      google_application_credentials:
        from_secret: google_application_credentials
      publish: true
